export const LoaderConfig = {
    Background: "src/sprites/backgrounds.jpg",
    bloodEternal: "src/sprites/BloodEternal.png",
    candles: "src/sprites/candles.png",
    flame0: "src/sprites/flame0.png",
    flame1: "src/sprites/flame1.png",
    flame2: "src/sprites/flame2.png",
    flame3: "src/sprites/flame3.png",
    flame4: "src/sprites/flame4.png",
    flame5: "src/sprites/flame5.png",
    flame6: "src/sprites/flame6.png",
    flame7: "src/sprites/flame7.png",
    flame8: "src/sprites/flame8.png",
    flame9: "src/sprites/flame9.png",
    flame10: "src/sprites/flame10.png",
    flame11: "src/sprites/flame11.png",
    flame12: "src/sprites/flame12.png",
    flame13: "src/sprites/flame13.png",
    flame14: "src/sprites/flame14.png",
    flame15: "src/sprites/flame15.png",
    flame16: "src/sprites/flame16.png",
    flame17: "src/sprites/flame17.png",
    flame18: "src/sprites/flame18.png",
    flame19: "src/sprites/flame19.png",
    flame20: "src/sprites/flame20.png",
    flame21: "src/sprites/flame21.png",
    flame22: "src/sprites/flame22.png",
    flame23: "src/sprites/flame23.png",
    flame24: "src/sprites/flame24.png",
    flame25: "src/sprites/flame25.png",
    flame26: "src/sprites/flame26.png",
    flame27: "src/sprites/flame27.png",
    flame28: "src/sprites/flame28.png",
    flame29: "src/sprites/flame29.png",
    flame30: "src/sprites/flame30.png",
    flame31: "src/sprites/flame31.png",
    flame32: "src/sprites/flame32.png",
    flame33: "src/sprites/flame33.png",
    flame34: "src/sprites/flame34.png",
    flame35: "src/sprites/flame35.png",
    flame36: "src/sprites/flame36.png",
    flame37: "src/sprites/flame37.png",
    flame38: "src/sprites/flame38.png",
    flame39: "src/sprites/flame39.png",
    flame40: "src/sprites/flame40.png",
    flame41: "src/sprites/flame41.png",
    flame42: "src/sprites/flame42.png",
    flame43: "src/sprites/flame43.png",
    flame44: "src/sprites/flame44.png",
    flame45: "src/sprites/flame45.png",
    flame46: "src/sprites/flame46.png",
    flame47: "src/sprites/flame47.png",
    flame48: "src/sprites/flame48.png",
    flame49: "src/sprites/flame49.png",
    flame50: "src/sprites/flame50.png",
    flame51: "src/sprites/flame51.png",
    flame52: "src/sprites/flame52.png",
    flame53: "src/sprites/flame53.png",
    flame54: "src/sprites/flame54.png",
    flame55: "src/sprites/flame55.png",
    flame56: "src/sprites/flame56.png",
    flame57: "src/sprites/flame57.png",
    flame58: "src/sprites/flame58.png",
    flame59: "src/sprites/flame59.png",
    flame60: "src/sprites/flame60.png",
    flame61: "src/sprites/flame61.png",
    flame62: "src/sprites/flame62.png",
    flame63: "src/sprites/flame63.png",

    slots0_0: "src/sprites/Symbols/slots0.png",
    slots1_0: "src/sprites/Symbols/slots1.png",
    slots2_0: "src/sprites/Symbols/slots2.png",
    slots3_0: "src/sprites/Symbols/slots3.png",
    slots4_0: "src/sprites/Symbols/slots4.png",
    slots5_0: "src/sprites/Symbols/slots5.png",
    slots6_0: "src/sprites/Symbols/slots6.png",
    slots7_0: "src/sprites/Symbols/slots7.png",
    slots8_0: "src/sprites/Symbols/slots8.png",
    slots9_0: "src/sprites/Symbols/slots9.png",
    slots10_0: "src/sprites/Symbols/slots10.png",
    slots11_0: "src/sprites/Symbols/slots11.png",
    slots12_0: "src/sprites/Symbols/slots12.png",
    slots13_0: "src/sprites/Symbols/slots13.png",
    slots14_0: "src/sprites/Symbols/slots14.png",
    slots15_0: "src/sprites/Symbols/slots15.png",

    reelBg: "src/sprites/reelBg.png",
    buttonBg: "src/sprites/buttonBg-Panel.png",
    winPanel: "src/sprites/winPanel.png",
    circleBg: "src/sprites/circleBg.png",
    minusButton: "src/sprites/minusButton.png",
    plusButton: "src/sprites/plusButton.png",
    blueCircle: "src/sprites/blueCircle.png",
    redCircle: "src/sprites/redCircle.png",
    greyCircle: "src/sprites/greyCircle.png",
    infoIcon: "src/sprites/infoIcon.png",
    soundOn: "src/sprites/soundOn.png",
    soundOff: "src/sprites/soundOff.png",
    settingButton: "src/sprites/settingButton.png",
    popupBgSprite: "src/sprites/popupBg.png",
    closeButton: "src/sprites/closeButton.png",
    headingBg: "src/sprites/headingBg.png",
    nextButton: "src/sprites/nextButton.png",
    previousButton: "src/sprites/previousButton.png",
    returnToGame: "src/sprites/returnToGame.png",
    blankCircle: "src/sprites/blankCircle.png",
    borderBottom: "src/sprites/bottomBorder.png",
    coinBg: "src/sprites/coinBg.png",
    redVampire: "src/sprites/RedVamp.png",
    blueVampire: "src/sprites/BlueVamp.png",
    payLine: "src/sprites/PayLine.png",
    winLine: "src/sprites/winLine.png",

    //Gamble
    insideGamble: "src/sprites/insideGamble.png",

    // winRing0: "src/sprites/WinRing1.png",
    // winRing1: "src/sprites/WinRing2.png",
    // winRing2: "src/sprites/WinRing3.png",
    // winRing3: "src/sprites/WinRing4.png",
    // winRing4: "src/sprites/WinRing5.png",
    winRing5: "src/sprites/WinRing6.png",
    // winRing6: "src/sprites/WinRing7.png",
    // winRing7: "src/sprites/WinRing8.png",
    // winRing8: "src/sprites/WinRing9.png",
    // winRing9: "src/sprites/WinRing10.png",
    // winRing10: "src/sprites/WinRing11.png",
    // winRing11: "src/sprites/WinRing12.png",
    // winRing12: "src/sprites/WinRing13.png",
    // winRing13: "src/sprites/WinRing14.png",

    //new Win 
    newWinRing0: "src/sprites/newwinRing0.png",
    newWinRing1: "src/sprites/newwinRing1.png",
    newWinRing2: "src/sprites/newwinRing2.png",
    newWinRing3: "src/sprites/newwinRing3.png",
    newWinRing4: "src/sprites/newwinRing4.png",

    RedSmoke0: "src/sprites/RedSmoke2.png",
    RedSmoke1: "src/sprites/RedSmoke3.png",
    RedSmoke2: "src/sprites/RedSmoke4.png",
    RedSmoke3: "src/sprites/RedSmoke5.png",
    RedSmoke4: "src/sprites/RedSmoke6.png",
    RedSmoke5: "src/sprites/RedSmoke7.png",
    RedSmoke6: "src/sprites/RedSmoke8.png",
    RedSmoke7: "src/sprites/RedSmoke9.png",
    RedSmoke8: "src/sprites/RedSmoke10.png",
    RedSmoke9: "src/sprites/RedSmoke11.png",
    RedSmoke10: "src/sprites/RedSmoke12.png",
    RedSmoke11: "src/sprites/RedSmoke13.png",
    RedSmoke12: "src/sprites/RedSmoke14.png",
    RedSmoke13: "src/sprites/RedSmoke15.png",
    RedSmoke14: "src/sprites/RedSmoke16.png",
    RedSmoke15: "src/sprites/RedSmoke17.png",
    RedSmoke16: "src/sprites/RedSmoke18.png",
    RedSmoke17: "src/sprites/RedSmoke19.png",
    RedSmoke18: "src/sprites/RedSmoke20.png",
    RedSmoke19: "src/sprites/RedSmoke21.png",
    RedSmoke20: "src/sprites/RedSmoke22.png",
    RedSmoke21: "src/sprites/RedSmoke23.png",
    RedSmoke22: "src/sprites/RedSmoke24.png",
    RedSmoke23: "src/sprites/RedSmoke25.png",
    RedSmoke24: "src/sprites/RedSmoke26.png",
    RedSmoke25: "src/sprites/RedSmoke27.png",
    RedSmoke26: "src/sprites/RedSmoke28.png",

    redReel0: "src/sprites/redReel0.png",
    redReel1: "src/sprites/redReel1.png",
    redReel2: "src/sprites/redReel2.png",
    redReel3: "src/sprites/redReel3.png",
    redReel4: "src/sprites/redReel4.png",
    redReel5: "src/sprites/redReel5.png",
    redReel6: "src/sprites/redReel6.png",
    redReel7: "src/sprites/redReel7.png",
    redReel8: "src/sprites/redReel8.png",
    redReel9: "src/sprites/redReel9.png",
    redReel10: "src/sprites/redReel10.png",
    redReel11: "src/sprites/redReel11.png",
    redReel12: "src/sprites/redReel12.png",
    redReel13: "src/sprites/redReel13.png",
    redReel14: "src/sprites/redReel14.png",
    redReel15: "src/sprites/redReel15.png",
    redReel16: "src/sprites/redReel16.png",
    redReel17: "src/sprites/redReel17.png",

    //purple Reel Container
    purpleReel0: "src/sprites/purpleReel0.png",
    purpleReel1: "src/sprites/purpleReel1.png",
    purpleReel2: "src/sprites/purpleReel2.png",
    purpleReel3: "src/sprites/purpleReel3.png",
    purpleReel4: "src/sprites/purpleReel4.png",
    purpleReel5: "src/sprites/purpleReel5.png",
    purpleReel6: "src/sprites/purpleReel6.png",
    purpleReel7: "src/sprites/purpleReel7.png",
    purpleReel8: "src/sprites/purpleReel8.png",
    purpleReel9: "src/sprites/purpleReel9.png",
    purpleReel10: "src/sprites/purpleReel10.png",
    purpleReel11: "src/sprites/purpleReel11.png",
    purpleReel12: "src/sprites/purpleReel12.png",
    purpleReel13: "src/sprites/purpleReel13.png",
    purpleReel14: "src/sprites/purpleReel14.png",
    purpleReel15: "src/sprites/purpleReel15.png",
    purpleReel16: "src/sprites/purpleReel16.png",
    purpleReel17: "src/sprites/purpleReel17.png",

    //Purple Symbol
    purpleSymbol0: "src/sprites/purpleSymbol0.png",
    purpleSymbol1: "src/sprites/purpleSymbol1.png",
    purpleSymbol2: "src/sprites/purpleSymbol2.png",
    purpleSymbol3: "src/sprites/purpleSymbol3.png",
    purpleSymbol4: "src/sprites/purpleSymbol4.png",
    purpleSymbol5: "src/sprites/purpleSymbol5.png",
    purpleSymbol6: "src/sprites/purpleSymbol6.png",
    purpleSymbol7: "src/sprites/purpleSymbol7.png",
    purpleSymbol8: "src/sprites/purpleSymbol8.png",
    purpleSymbol9: "src/sprites/purpleSymbol9.png",
    purpleSymbol10: "src/sprites/purpleSymbol10.png",
    purpleSymbol11: "src/sprites/purpleSymbol11.png",
    purpleSymbol12: "src/sprites/purpleSymbol12.png",
    purpleSymbol13: "src/sprites/purpleSymbol13.png",
    purpleSymbol14: "src/sprites/purpleSymbol14.png",
    purpleSymbol15: "src/sprites/purpleSymbol15.png",
    purpleSymbol16: "src/sprites/purpleSymbol16.png",
    purpleSymbol17: "src/sprites/purpleSymbol17.png",
    purpleSymbol18: "src/sprites/purpleSymbol18.png",
    purpleSymbol19: "src/sprites/purpleSymbol19.png",
    purpleSymbol20: "src/sprites/purpleSymbol20.png",
    purpleSymbol21: "src/sprites/purpleSymbol21.png",
    purpleSymbol22: "src/sprites/purpleSymbol22.png",
    purpleSymbol23: "src/sprites/purpleSymbol23.png",
    purpleSymbol24: "src/sprites/purpleSymbol24.png",
    purpleSymbol25: "src/sprites/purpleSymbol25.png",
    purpleSymbol26: "src/sprites/purpleSymbol26.png",
    purpleSymbol27: "src/sprites/purpleSymbol27.png",
    purpleSymbol28: "src/sprites/purpleSymbol28.png",
    purpleSymbol29: "src/sprites/purpleSymbol29.png",
    purpleSymbol30: "src/sprites/purpleSymbol30.png",
    purpleSymbol31: "src/sprites/purpleSymbol31.png",
    purpleSymbol32: "src/sprites/purpleSymbol32.png",
    purpleSymbol33: "src/sprites/purpleSymbol33.png",
    purpleSymbol34: "src/sprites/purpleSymbol34.png",
    purpleSymbol35: "src/sprites/purpleSymbol35.png",

    //male Vampire
    maleVampire0: "src/sprites/mVampire0.png",
    maleVampire1: "src/sprites/mVampire1.png",
    maleVampire2: "src/sprites/mVampire2.png",
    maleVampire3: "src/sprites/mVampire3.png",
    maleVampire4: "src/sprites/mVampire4.png",
    maleVampire5: "src/sprites/mVampire5.png",
    maleVampire6: "src/sprites/mVampire6.png",
    maleVampire7: "src/sprites/mVampire7.png",
    maleVampire8: "src/sprites/mVampire8.png",
    maleVampire9: "src/sprites/mVampire9.png",
    maleVampire10: "src/sprites/mVampire10.png",
    maleVampire11: "src/sprites/mVampire11.png",
    maleVampire12: "src/sprites/mVampire12.png",
    maleVampire13: "src/sprites/mVampire13.png",

    // Female Vampire
    womanVampire0:"src/sprites/wVampire0.png",
    womanVampire1:"src/sprites/wVampire1.png",
    womanVampire2:"src/sprites/wVampire2.png",
    womanVampire3:"src/sprites/wVampire3.png",
    womanVampire4:"src/sprites/wVampire4.png",
    womanVampire5:"src/sprites/wVampire5.png",
    womanVampire6:"src/sprites/wVampire6.png",
    womanVampire7:"src/sprites/wVampire7.png",
    womanVampire8:"src/sprites/wVampire8.png",
    womanVampire9:"src/sprites/wVampire9.png",
    womanVampire10:"src/sprites/wVampire10.png",
    womanVampire11:"src/sprites/wVampire11.png",
    womanVampire12:"src/sprites/wVampire12.png",
    womanVampire13:"src/sprites/wVampire13.png",

    //BloodSplash
    bloodSplash: "src/sprites/bloodSplash.png",
    turboButton: "src/sprites/turboButton.png",
    stopButton: "src/sprites/stopSpin.png",

    turboSpin0: "src/sprites/turboSpin0.png",
    turboSpin1: "src/sprites/turboSpin1.png",
    turboSpin2: "src/sprites/turboSpin2.png",
    turboSpin3: "src/sprites/turboSpin3.png",
    turboSpin4: "src/sprites/turboSpin4.png",
    turboSpin5: "src/sprites/turboSpin5.png",
    turboSpin6: "src/sprites/turboSpin6.png",
    turboSpin7: "src/sprites/turboSpin7.png",
    turboSpin8: "src/sprites/turboSpin8.png",
    turboSpin9: "src/sprites/turboSpin9.png",
    turboSpin10: "src/sprites/turboSpin10.png",
    turboSpin11: "src/sprites/turboSpin11.png",
    turboSpin12: "src/sprites/turboSpin12.png",
    turboSpin13: "src/sprites/turboSpin13.png",
    turboSpin14: "src/sprites/turboSpin14.png",
    turboSpin15: "src/sprites/turboSpin15.png",
    turboSpin16: "src/sprites/turboSpin16.png",
    turboSpin17: "src/sprites/turboSpin17.png",
    turboSpin18: "src/sprites/turboSpin18.png",

    //Coin Anim
    coin0: "src/sprites/Coin0.png",
    coin1: "src/sprites/Coin1.png",
    coin2: "src/sprites/Coin2.png",
    coin3: "src/sprites/Coin3.png",
    coin4: "src/sprites/Coin4.png",
    coin5: "src/sprites/Coin5.png",
    coin6: "src/sprites/Coin6.png",
    coin7: "src/sprites/Coin7.png",
    coin8: "src/sprites/Coin8.png",
    coin9: "src/sprites/Coin9.png",
    coin10: "src/sprites/Coin10.png",
    coin11: "src/sprites/Coin11.png",
    coin12: "src/sprites/Coin12.png",
    coin13: "src/sprites/Coin13.png",
    coin14: "src/sprites/Coin14.png",
    coin15: "src/sprites/Coin15.png",
}

export const LoaderSoundConfig: any = {
    backgroundMusic : "src/sounds/backgroundMusic.mp3",
    onSpin :  "/src/sounds/spinRoll.mp3",
    spinButton: "src/sounds/spinButton.mp3",
    winMusic: "src/sounds/winning.mp3",
    buttonpressed: "src/sounds/Game-Button.mp3",
}